### ISSUE TITLE
About Embedding

### ISSUE THREAD

**Issue by LMY-nlp0701** [lephong/mulrel-nel#10]
I have read your paper and part of the code.
At the same time, I also read the **Ganea and Hofmann(2017)** paper and the complete code.

1. Entity Embeddings from **Ganea and Hofmann(2017)** . as far as I know，**Ganea and Hofmann(2017)** did not provide the Entity Embeddings. Are you retraining with his code?

2.  In your code, **snd_word_voca** from "data/generated/embeddings/word_ent_embs/glove" folder.
Then, what does **snd_word_voca** mean ?

3.  In your code, **word_voca** from "data/generated/embeddings/word_ent_embs" folder. 
Then, is **word_voca** trained by  **snd_word_voca** using Equation 4?

Thank you for your answer. If you are disturbed, please forgive me.

**Comment by lephong** [comment]
1. They actually did. Please have a look at their source code page https://github.com/dalab/deep-ed 

2 & 3. word_voca is the vocabulary for the local model, which is identical to G&H. snd_word_voca is the vocabulary used in our global model. The first is from word2vec, the second is from glove. We fixed them during training.
