### ISSUE TITLE
Using model on different knowledge base and different train and test files

### ISSUE THREAD

**Issue by shirakad** [lephong/mulrel-nel#11]
Hi,
I'm looking for the knowledge base format in order to build one of my own, is there any reference for README file that explains about the format?
In addition, I would like to create my own train and test files, is there is any README that explains about the format?

Is it possible to train your model with new KB, train file, test file?
Thanks !

**Comment by lephong** [comment]
In this work, all the used data (and the format) is from https://github.com/dalab/deep-ed. You might want to have a look at it.

**Comment by shirakad** [comment]
Hi, Thanks for the reference, 
I've added another question - 
Is it possible to train your model with new KB, train file, test file?
