### ISSUE TITLE
Global model parameters

### ISSUE THREAD

**Issue by lej-la** [lephong/mulrel-nel#16]
What exactly are the two parameters of your global model (MulRelRanker)?
 
1) If I understand correctly `rel_embs` is the relation embedding matrix **R**.
2) What does `ew_embs` stand for? I guess it corresponds to the matrix **D** in your paper, but it's not clear to me in there either.

**Comment by lephong** [comment]
You were right. Please bear in mind that, because those matrices are diagonal (an R and a D are for one relation), we represent each R (and each D) as a vector. Therefore rel_embs (n_rels x emb_dims) are for n_rels matrices Rs. Similarly to matrices Ds.

**Comment by lej-la** [comment]
Thank you very much for your response.

So **R** is a diagonal matrix representing one relation and in the code it is represented as a vector (_relation embedding_) and rel_embs is a matric containing vectors Rs for all relations (n_rels).

I understand that **D** has the same shape as **R**, but what is the conceptual meaning of it? And what does the name `ew_embs` stand for?

**Comment by lephong** [comment]
Intuitively, a matrix D_k (corresponding to a matrix R_k for a relation k, see Eq 4) is to score how much the contexts of the two entity mentions i and j support relation k. Matrix R_k is to score how much two entity candidates ei and ej support relation k (the Eq before Eq 4).

**Comment by lephong** [comment]
Re the name `ew_embs`, I actually don't remember :(

**Comment by lej-la** [comment]
Thank you :)
