### ISSUE TITLE
read_conll_file function

### ISSUE THREAD

**Issue by mickvanhulst** [lephong/mulrel-nel#20]
Dear author,

I am wondering what the 'read_conll_file' (see dataset.py) function is responsible for? It significantly increases the scores by using it for the secondary local context, so I am really curious..?

**Comment by lephong** [comment]
It is for reading conll-format files. 
Can you say more about the problem of increasing the scores (compared to what)?

**Comment by mickvanhulst** [comment]
My apologies for being unclear: Using the function increases the resulting F1 scores significantly (without it, I was not able to obtain the results that are described in the paper). The aforementioned function loads the conll files and then uses this for a secondary local context.

What is the added value of the conll files over the original training/test (csv) files that were provided?

**Comment by lephong** [comment]
Ah, I see, the problem while I need this function is that I need the context between two given mentions. CSV files don't provide that. Without these contexts, every mentions pair will have the same attention score. That's why the performance will drop without it.

**Comment by mickvanhulst** [comment]
I see, thank you for the clarification and have a nice evening :).
