### ISSUE TITLE
About the F1 metric

### ISSUE THREAD

**Issue by jianyucai** [lephong/mulrel-nel#23]
Hi, thanks for your code. I noticed that you choose F1 as the evaluation metric, but I am a little confused on its definition.

https://github.com/lephong/mulrel-nel/blob/db14942450f72c87a4d46349860e96ef2edf353d/nel/dataset.py#L187-L203

We know that precision and recall are defined by:
precision = tp / (tp + fp)
recall = tp / (tp + fn)

However, this task is not a binary classification task. So I'm wondering how to define tp, tn, fp and fn.

**Comment by lephong** [comment]
It's pretty straight-forward to extend precision/recall to multi-class classification. In this case, true positive = the number of predicted y_i = golden y_i.

**Comment by jianyucai** [comment]
Thanks.
