### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by CAROLZXYZXY** [lephong/mulrel-nel#3]
Hi,

Thanks for the code! When I downloaded all the file, and started to train with: python -u -m nel.main --mode train --n_rels 3 --mulrel_type ment-norm --model_path model , it comes with the error:
Traceback (most recent call last):
  File "/home/xinyi/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xinyi/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xinyi/mulrel-nel/nel/main.py", line 159, in <module>
    ranker.train(conll.train, dev_datasets, config)
  File "/home/xinyi/mulrel-nel/nel/ed_ranker.py", line 327, in train
    loss = loss.cpu().data.numpy()[0]
IndexError: too many indices for array

The error comes after the output:
recall 0.9828316610925306
aida-B #dev docs 232
recall 0.9847560975609756
msnbc #dev docs 20
recall 0.9436038514442916
aquaint #dev docs 50
recall 0.9066147859922179
ace2004 #dev docs 35
recall 0.9169804554419939
clueweb #dev docs 320
recall 0.923418095801301
wikipedia #dev docs 318
creating optimizer

Thanks a lot!

**Comment by CAROLZXYZXY** [comment]
I guess we use the different version of numpy, can you please provide your configuration? Thanks a lot!

**Comment by lephong** [comment]
I think the error comes from the diff in Pytorch versions. I used pytorch 0.3 . 
In fact, if you look at issue #2, a quick way to get rid of the errror is to remove [0], i.e. loss.cpu().data.numpy()
