### ISSUE TITLE
Does "--mulrel_type rel-norm" really result in rel-norm?

### ISSUE THREAD

**Issue by kwashio** [lephong/mulrel-nel#5]
Hi, thanks for the code.

I found that the option '--mulrel_type rel-norm'  doesn't change the model in the class MulRelRanker.
`python -u -m nel.main --mode train --n_rels 3 --mulrel_type rel-norm --model_path model` leads to the model config as follows:

```
---------------- model config -----------------
training True
emb_dims 300
freeze_embs True
hid_dims 100
tok_top_n 25
margin 0.01
df 0.5
n_loops 10
n_rels 3
dr 0.3
ew_hid_dims 300
max_dist 1000
ent_top_n 1000
oracle False
ent_ent_comp bilinear
ctx_comp bow
mode ment-norm
first_head_uniform False
use_pad_ent False
use_stargmax False
use_local True
use_local_only False
freeze_local False
_coh_ctx_vecs None
```
The mode is still ment-norm.
I think that this is because [the line 40 in nel/mulrel_ranker.py](https://github.com/lephong/mulrel-nel/blob/master/nel/mulrel_ranker.py#L40).
The config does not have 'mode' as its key. Thus, self.mode is always 'ment-norm'.

Is it OK?

**Comment by lephong** [comment]
I have fixed it. This is a result of cleaning the source code some months ago. Sorry for letting you wait.
