### ISSUE TITLE
About Ntee model

### ISSUE THREAD

**Issue by JieyuZ2** [lephong/mulrel-nel#8]
It seems like it use ntee model for pre-rank without training it. It is wield. Can you provide the trained weights of ntee model?

**Comment by lephong** [comment]
The NTEE model here is nothing more than computing the distance between the average of contextual word embeddings and an entity embedding. Therefore, it doesn't have any more parameters rather than the pre-trained embeddings. Note that the pre-trained embeddings are kept fixed during training.

**Comment by peblair** [comment]
@lephong Sorry for digging up an old issue, but, following up on this, how does [`self.linear`](https://github.com/lephong/mulrel-nel/blob/db14942450f72c87a4d46349860e96ef2edf353d/nel/ntee.py#L18) get its weight set, then? The only possible place I see is `create_ntee_from_components`, which is not called anywhere. It does appear that NTEE has this one parameter, and [it is used](https://github.com/lephong/mulrel-nel/blob/db14942450f72c87a4d46349860e96ef2edf353d/nel/ntee.py#L26) to produce the results of the forward pass.
